name: Build & Push Backend to ECR

on:
  push:
    branches:
      - main  # Trigger when the main branch is updated

jobs:
  build:
    name: Build Backend Image & Push to ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Allows using OIDC
      contents: read  # Allows reading the source code

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Assume AWS role via OIDC
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-3
        role-to-assume: arn:aws:iam::380426548948:role/backend-app-new-GitHubActionsOIDCRole  # Updated role ARN for backend

    # Step 3: Update IAM Policy to include InitiateLayerUpload
    - name: Update IAM Policy to include InitiateLayerUpload
      run: |
        aws iam create-policy-version \
          --policy-arn arn:aws:iam::380426548948:policy/backend-app-new-GitHubActionsECRPolicy \
          --policy-document '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Action": [
                  "ecr:GetAuthorizationToken"
                ],
                "Effect": "Allow",
                "Resource": "*"
              },
              {
                "Action": [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:PutImage",
                  "ecr:BatchGetImage",
                  "ecr:InitiateLayerUpload"
                ],
                "Effect": "Allow",
                "Resource": "arn:aws:ecr:eu-west-3:380426548948:repository/*"
              }
            ]
          }' \
          --set-as-default

    # Step 4: Log in to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 5: Build, tag, and push the image to ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: backend-app  # Backend ECR repository
        IMAGE_TAG: latest  # Tag for the latest version
      run: |
        # Build the Docker image with a tag based on commit SHA and the 'latest' tag
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Push the image to ECR with all tags
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
