name: Build & Push Backend to ECR

on:
  push:
    branches:
      - main  # Trigger when the main branch is updated

jobs:
  build:
    name: Build Backend Image & Push to ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Allows using OIDC
      contents: read  # Allows reading the source code

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Assume AWS role via OIDC
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-3
        role-to-assume: arn:aws:iam::380426548948:role/backend-app-new-GitHubActionsOIDCRole  # Updated role ARN for backend

    # Step 3: Log in to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Build, tag, and push the image to ECR
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: backend-app # Backend ECR repository
        IMAGE_TAG: latest  # Tag for the latest version
      run: |
        # Build the Docker image with a tag based on commit SHA and the 'latest' tag
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Push the image to ECR with all tags
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          # Step 5: Download task definition
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition backend-task-def --query taskDefinition > task-definition.json

    # Step 6: Fill in the new image ID in the Amazon ECS task definition
    - name: Render ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: back-container
        image: ${{ steps.build-image.outputs.image }}

    # Step 7: Deploy Amazon ECS task definition
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: back-service
        cluster: back-cluster
        wait-for-service-stability: true
    
